name: Close Stale PRs
on:
  workflow_dispatch: null
permissions:
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639
      with:
        days-before-issue-stale: -1
        days-before-issue-close: -1
        days-before-pr-stale: 3
        days-before-pr-close: 0
        stale-pr-message: This PR has been inactive for 72 hours. Closing to keep
          the queue clean.
        close-pr-message: This PR was closed because it has been stalled for 72 hours.
          Feel free to magically reopen it if you want to continue working on it!
        exempt-pr-labels: keep-alive
